<?php
return [
    'stats' => [
        'str' => 'strength',
        'dex' => 'dexterity',
        'con' => 'constitution',
        'int' => 'intelligence',
        'wis' => 'wisdom',
        'cha' => 'charisma',
    ],
    'skills' => [
        'acrobatics' => 'dex',
        'animal_handling' => 'wis',
        'arcana' => 'int',
        'athletics' => 'str',
        'deception' => 'cha',
        'history' => 'int',
        'insight' => 'wis',
        'intimidation' => 'cha',
        'investigation' => 'int',
        'medicine' => 'wis',
        'nature' => 'int',
        'perception' => 'wis',
        'performance' => 'cha',
        'persuasion' => 'cha',
        'religion' => 'int',
        'sleight_of_hand' => 'dex',
        'stealth' => 'dex',
        'survival' => 'wis',
    ],
    'modifier' => [
        'baseline' => 10,
        'step' => 2,
    ],
    'feature_types' => [
        'action' => 'Action',
        'bonus_action' => 'Bonus action',
        'reaction' => 'Reaction',
    ],
];
